# Generated by Django 5.1.8 on 2025-04-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogames', '0002_alter_videogame_genre_alter_videogame_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame',
            name='gameImg',
            field=models.ImageField(blank=True, null=True, upload_to='contents/'),
        ),
    ]
